# Generated by Django 3.2.10 on 2022-03-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220227_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkDownTest',
        ),
    ]
