# Generated by Django 3.2.10 on 2022-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_markdowntest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('taste', models.TextField()),
                ('stars', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
